######################################################################
# Automatically generated by qmake (3.0) Tue Jan 10 17:23:42 2017
######################################################################

TEMPLATE = app
TARGET = "spectrogram"
INCLUDEPATH += .
QT += gui widgets
QT += charts

LIBS += -liir

SOURCES += main.cpp
SOURCES += Helpful_functions.cpp
SOURCES += server.cpp
SOURCES += NeuralNetwork/NeuralNetwork.cpp
