######################################################################
# Automatically generated by qmake (3.0) Tue Jan 10 17:23:42 2017
######################################################################

TEMPLATE = app
TARGET = "spectrogram"
INCLUDEPATH += .
QT += gui widgets


SOURCES += main.cpp 
SOURCES += filt.cpp
